services:
  redis-master:
    image: redis:7-alpine
    container_name: redis-master
    hostname: redis-master
    ports:
      - "6379:6379"
    volumes:
      - ./config/redis-master.conf:/usr/local/etc/redis/redis.conf
      - redis-master-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - redis-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    environment:
      - REDIS_REPLICATION_MODE=master
    labels:
      - "redis.role=master"
      - "redis.port=6379"

  redis-replica-1:
    image: redis:7-alpine
    container_name: redis-replica-1
    hostname: redis-replica-1
    ports:
      - "6380:6379"
    volumes:
      - ./config/redis-replica-1.conf:/usr/local/etc/redis/redis.conf
      - redis-replica-1-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - redis-network
    restart: unless-stopped
    depends_on:
      redis-master:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT=6379
    labels:
      - "redis.role=replica"
      - "redis.port=6380"

  redis-replica-2:
    image: redis:7-alpine
    container_name: redis-replica-2
    hostname: redis-replica-2
    ports:
      - "6381:6379"
    volumes:
      - ./config/redis-replica-2.conf:/usr/local/etc/redis/redis.conf
      - redis-replica-2-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - redis-network
    restart: unless-stopped
    depends_on:
      redis-master:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT=6379
    labels:
      - "redis.role=replica"
      - "redis.port=6381"

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    hostname: redis-commander
    ports:
      - "8081:8081"
    networks:
      - redis-network
    restart: unless-stopped
    depends_on:
      - redis-master
      - redis-replica-1
      - redis-replica-2
    environment:
      - REDIS_HOSTS=local:redis-master:6379,replica1:redis-replica-1:6379,replica2:redis-replica-2:6379
    labels:
      - "service.type=monitoring"

volumes:
  redis-master-data:
    driver: local
  redis-replica-1-data:
    driver: local
  redis-replica-2-data:
    driver: local

networks:
  redis-network:
    driver: bridge
