services:
  redis-master:
    image: redis:7-alpine
    container_name: redis-master
    hostname: redis-master
    ports:
      - "6379:6379"
    volumes:
      - ./config/redis-master.conf:/usr/local/etc/redis/redis.conf
      - redis-master-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-network:
        ipv4_address: 192.168.55.10
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_master_password_2024", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    environment:
      - REDIS_REPLICATION_MODE=master
    labels:
      - "redis.role=master"
      - "redis.port=6379"

  redis-replica-1:
    image: redis:7-alpine
    container_name: redis-replica-1
    hostname: redis-replica-1
    ports:
      - "6380:6379"
    volumes:
      - ./config/redis-replica-1.conf:/usr/local/etc/redis/redis.conf
      - redis-replica-1-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-network:
        ipv4_address: 192.168.55.11
    restart: unless-stopped
    depends_on:
      redis-master:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_master_password_2024", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=192.168.55.10
      - REDIS_MASTER_PORT=6379
    labels:
      - "redis.role=replica"
      - "redis.port=6380"

  redis-replica-2:
    image: redis:7-alpine
    container_name: redis-replica-2
    hostname: redis-replica-2
    ports:
      - "6381:6379"
    volumes:
      - ./config/redis-replica-2.conf:/usr/local/etc/redis/redis.conf
      - redis-replica-2-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-network:
        ipv4_address: 192.168.55.12
    restart: unless-stopped
    depends_on:
      redis-master:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_master_password_2024", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=192.168.55.10
      - REDIS_MASTER_PORT=6379
    labels:
      - "redis.role=replica"
      - "redis.port=6381"

  redis-sentinel-1:
    image: redis:7-alpine
    container_name: redis-sentinel-1
    hostname: redis-sentinel-1
    ports:
      - "26379:26379"
    volumes:
      - ./sentinel-configs/sentinel-1:/usr/local/etc/redis
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    networks:
      redis-network:
        ipv4_address: 192.168.55.20
    restart: unless-stopped
    depends_on:
      redis-master:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "26379", "-a", "redis_sentinel_password_2024", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    environment:
      - REDIS_SENTINEL_MODE=yes
    labels:
      - "redis.role=sentinel"
      - "redis.port=26379"

  redis-sentinel-2:
    image: redis:7-alpine
    container_name: redis-sentinel-2
    hostname: redis-sentinel-2
    ports:
      - "26380:26379"
    volumes:
      - ./sentinel-configs/sentinel-2:/usr/local/etc/redis
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    networks:
      redis-network:
        ipv4_address: 192.168.55.21
    restart: unless-stopped
    depends_on:
      redis-master:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "26379", "-a", "redis_sentinel_password_2024", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    environment:
      - REDIS_SENTINEL_MODE=yes
    labels:
      - "redis.role=sentinel"
      - "redis.port=26380"

  redis-sentinel-3:
    image: redis:7-alpine
    container_name: redis-sentinel-3
    hostname: redis-sentinel-3
    ports:
      - "26381:26379"
    volumes:
      - ./sentinel-configs/sentinel-3:/usr/local/etc/redis
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    networks:
      redis-network:
        ipv4_address: 192.168.55.22
    restart: unless-stopped
    depends_on:
      redis-master:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "26379", "-a", "redis_sentinel_password_2024", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    environment:
      - REDIS_SENTINEL_MODE=yes
    labels:
      - "redis.role=sentinel"
      - "redis.port=26381"

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    hostname: redisinsight
    ports:
      - "8001:5540"
    volumes:
      - ./redisinsight-databases.json:/usr/src/app/redisinsight/api/dist/databases.json
      - ./redisinsight-config.json:/usr/src/app/redisinsight/api/dist/config.json
    networks:
      redis-network:
        ipv4_address: 192.168.55.30
    restart: unless-stopped
    depends_on:
      - redis-master
      - redis-replica-1
      - redis-replica-2
    environment:
      - RI_PRE_SETUP_DATABASES_PATH=/usr/src/app/redisinsight/api/dist/databases.json
      - RI_APP_PORT=5540
      - RI_APP_HOST=0.0.0.0
    labels:
      - "service.type=monitoring"

volumes:
  redis-master-data:
    driver: local
  redis-replica-1-data:
    driver: local
  redis-replica-2-data:
    driver: local

networks:
  redis-network:
    name: redisnet
    attachable: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.55.0/24
          gateway: 192.168.55.1