#!/bin/bash

# Redis Sentinel Initialization Script
# This script reads Docker secrets and generates Sentinel configuration

set -e

# Read secrets
REDIS_MASTER_PASSWORD=$(cat /run/secrets/redis_master_password 2>/dev/null || echo "redis_master_password_2024")
REDIS_SENTINEL_PASSWORD=$(cat /run/secrets/redis_sentinel_password 2>/dev/null || echo "redis_sentinel_password_2024")

# Get environment variables
SENTINEL_ANNOUNCE_IP=${SENTINEL_ANNOUNCE_IP:-192.168.55.20}
SENTINEL_ANNOUNCE_PORT=${SENTINEL_ANNOUNCE_PORT:-26379}
MASTER_HOST=${MASTER_HOST:-192.168.55.10}
MASTER_PORT=${MASTER_PORT:-6379}
QUORUM=${QUORUM:-2}

# Create Sentinel configuration with secret-based passwords
cat > /usr/local/etc/redis/sentinel.conf << EOF
# Redis Sentinel Configuration
# Port and Network
port 26379
bind 0.0.0.0
protected-mode yes

# Security
requirepass "$REDIS_SENTINEL_PASSWORD"

# Sentinel Configuration
sentinel monitor mymaster $MASTER_HOST $MASTER_PORT $QUORUM
sentinel auth-pass mymaster $REDIS_MASTER_PASSWORD
sentinel down-after-milliseconds mymaster 5000
sentinel failover-timeout mymaster 10000
sentinel deny-scripts-reconfig yes

# Sentinel Announcement
sentinel announce-ip "$SENTINEL_ANNOUNCE_IP"
sentinel announce-port $SENTINEL_ANNOUNCE_PORT

# Logging
loglevel notice
logfile ""
syslog-enabled no

# Notifications (disabled - scripts not available)
# sentinel notification-script mymaster /var/redis/notify.sh
# sentinel client-reconfig-script mymaster /var/redis/reconfig.sh

# Advanced Sentinel Settings
sentinel resolve-hostnames yes
sentinel announce-hostnames yes
sentinel config-epoch mymaster 11
sentinel current-epoch 11
# Generated by CONFIG REWRITE
dir "/data"
latency-tracking-info-percentiles 50 99 99.9
user default on sanitize-payload #e1a1d84ea07a7a1b6a6e612e72f8d8304e7f643a653e1039327e5160d9ecdb46 ~* &* +@all
sentinel myid dc598f9081320ae84353e8c7e8ee4ca007079898
sentinel leader-epoch mymaster 11

sentinel known-replica mymaster 192.168.55.11 6379
sentinel known-replica mymaster 192.168.55.10 6379

sentinel known-sentinel mymaster 192.168.55.22 26379 e253961c2dbc4e450b4bae3df7624bd3c65b372a
sentinel known-sentinel mymaster 192.168.55.21 26379 b8faa59d6e9368a6f120c6dac43a519b8a230fff
EOF

echo "Redis Sentinel configuration generated with secret-based passwords"
